name: Hello

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: hello raju
        run: |
          echo "hello github action"
          echo "i am practicing github action"
